#MODELLING

In [1]:
#Import all of the library that we're going to use
import pandas as pd
import numpy as np
import tensorflow as tf

In [9]:
!curl -L -o 'data tourism.xlsx' "https://docs.google.com/spreadsheets/d/1ealGhVIkeDGOoAGTbsml_SHqjIQaie_x2sssE8k1ISM/export?format=xlsx"

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   413    0   413    0     0   1585      0 --:--:-- --:--:-- --:--:--  1582
100  392k    0  392k    0     0   303k      0 --:--:--  0:00:01 --:--:-- 3843k


In [10]:
df_tourism = pd.read_excel('data tourism.xlsx',sheet_name='tourism_with_id')

In [11]:
df_tourism.head()

Place_Id                         Place_Name  Gambar  \
0         1            Monumen Nasional(Monas)     NaN   
1         2                           Kota Tua     NaN   
2         3               Dunia Fantasi(Dufan)     NaN   
3         4  Taman Mini Indonesia Indah (TMII)     NaN   
4         5    Taman Impian Jaya Ancol (Ancol)     NaN   

                                         Description  Sentiment  Penghujan  \
0  Monumen Nasional atau yang populer disingkat d...   0.380043          0   
1  Kota tua di Jakarta, yang juga bernama Kota Tu...   0.306300          1   
2  Dunia Fantasi atau disebut juga Dufan adalah t...   0.192350          0   
3  Taman Mini Indonesia Indah merupakan suatu kaw...   0.295739          0   
4  Taman Impian Jaya Ancol merupakan sebuah objek...   0.140687          0   

   Kemarau       Category  Budaya  Taman Hiburan  Cagar Alam  Bahari  \
0        1         Budaya       1              0           0       0   
1        0         Budaya       1              0           0       0   
2        1  Taman Hiburan       0              1           0       0   
3        1  Taman Hiburan       0              1           0       0   
4        1  Taman Hiburan       0              1           0       0   

   Pusat Perbelanjaan  Tempat Ibadah     City  Rating       Lat        Long  
0                   0              0  Jakarta     4.6 -6.175392  106.827153  
1                   0              0  Jakarta     4.6 -6.137645  106.817125  
2                   0              0  Jakarta     4.6 -6.125312  106.833538  
3                   0              0  Jakarta     4.5 -6.302446  106.895156  
4                   0              0  Jakarta     4.5 -6.117333  106.857995

In [32]:
dataset = df_tourism[['Bahari', 'Budaya', 'Cagar Alam','Pusat Perbelanjaan',  'Tempat Ibadah','Taman Hiburan','Penghujan','Kemarau','Sentiment','Rating']]

In [34]:
dataset

Bahari  Budaya  Cagar Alam  Pusat Perbelanjaan  Tempat Ibadah  \
0         0       1           0                   0              0   
1         0       1           0                   0              0   
2         0       0           0                   0              0   
3         0       0           0                   0              0   
4         0       0           0                   0              0   
..      ...     ...         ...                 ...            ...   
491       0       0           0                   1              0   
492       0       0           0                   1              0   
493       0       0           0                   1              0   
494       0       0           0                   1              0   
495       0       0           0                   1              0   

     Taman Hiburan  Penghujan  Kemarau  Sentiment  Rating  
0                0          0        1   0.380043     4.6  
1                0          1        0   0.306300     4.6  
2                1          0        1   0.192350     4.6  
3                1          0        1   0.295739     4.5  
4                1          0        1   0.140687     4.5  
..             ...        ...      ...        ...     ...  
491              0          1        0   0.287445     4.3  
492              0          0        1   0.189665     4.5  
493              0          1        0   0.408663     4.4  
494              0          1        0   0.164591     4.8  
495              0          0        1   0.164591     4.7  

[496 rows x 10 columns]

In [65]:
dataset = dataset.astype('float64')

In [66]:
dataset.dtypes

Bahari                float64
Budaya                float64
Cagar Alam            float64
Pusat Perbelanjaan    float64
Tempat Ibadah         float64
Taman Hiburan         float64
Penghujan             float64
Kemarau               float64
Sentiment             float64
Rating                float64
dtype: object

In [70]:
np_data = dataset.to_numpy()
np_data

array([[0.        , 1.        , 0.        , ..., 1.        , 0.38004271,
        4.6       ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.30630007,
        4.6       ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.19235043,
        4.6       ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.40866278,
        4.4       ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.16459101,
        4.8       ],
       [0.        , 0.        , 0.        , ..., 1.        , 0.16459101,
        4.7       ]])

In [84]:
data_final = pd.DataFrame(np_data)
# data_final
data_final

0    1    2    3    4    5    6    7         8    9
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.380043  4.6
1    0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.306300  4.6
2    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.192350  4.6
3    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.295739  4.5
4    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.140687  4.5
..   ...  ...  ...  ...  ...  ...  ...  ...       ...  ...
491  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.287445  4.3
492  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.189665  4.5
493  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.408663  4.4
494  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.164591  4.8
495  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.164591  4.7

[496 rows x 10 columns]

In [69]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 496 entries, 0 to 495
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Bahari              496 non-null    float64
 1   Budaya              496 non-null    float64
 2   Cagar Alam          496 non-null    float64
 3   Pusat Perbelanjaan  496 non-null    float64
 4   Tempat Ibadah       496 non-null    float64
 5   Taman Hiburan       496 non-null    float64
 6   Penghujan           496 non-null    float64
 7   Kemarau             496 non-null    float64
 8   Sentiment           496 non-null    float64
 9   Rating              496 non-null    float64
dtypes: float64(10)
memory usage: 38.9 KB


In [157]:
data_final

0    1    2    3    4    5    6    7         8    9
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.380043  4.6
1    0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.306300  4.6
2    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.192350  4.6
3    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.295739  4.5
4    0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.140687  4.5
..   ...  ...  ...  ...  ...  ...  ...  ...       ...  ...
491  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.287445  4.3
492  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.189665  4.5
493  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.408663  4.4
494  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.164591  4.8
495  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.164591  4.7

[496 rows x 10 columns]

In [85]:
data_final.to_csv('data_final.csv',index=False)

In [158]:
data_final.head()

0    1    2    3    4    5    6    7         8    9
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.380043  4.6
1  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.306300  4.6
2  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.192350  4.6
3  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.295739  4.5
4  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.140687  4.5

In [159]:
dataset_final_type =  tf.constant(data_final, dtype=tf.float32)

In [160]:
def cosine_similarity(v1, v2):
    v1_norm = tf.nn.l2_normalize(v1, axis=-1)
    v2_norm = tf.nn.l2_normalize(v2, axis=-1)
    return tf.reduce_sum(tf.multiply(v1_norm, v2_norm), axis=-1)

In [209]:
def enhanced_similarity(features, user_input, ratings, sentiments, alpha=0.4, beta=0.6):
    # Calculate cosine similarity between user input and feature vectors
    sim_scores = cosine_similarity(features, user_input)
    ratings_scaled = (ratings - tf.reduce_min(ratings)) / (tf.reduce_max(ratings) - tf.reduce_min(ratings))
    sentiments_scaled = (sentiments - tf.reduce_min(sentiments)) / (tf.reduce_max(sentiments) - tf.reduce_min(sentiments))
    final_scores = alpha * sim_scores + beta * (0.4 * ratings_scaled + 0.6 * sentiments_scaled)
    return final_scores

In [210]:
features = tf.constant([sublist[0:-2] for sublist in np_data], tf.float32)
# Bahari, Budaya, Cagar Alam, Pusat Perbelanjaan, Tempat Ibadah, Taman Hiburan
user_input = tf.constant([0, 1, 0, 1, 1, 0, 0, 1], tf.float32) # budaya,cagar alam, pusat perbelanjaan, kemarau
ratings = tf.constant([row[-1] for row in np_data],  tf.float32)
sentiments = tf.constant([row[-2] for row in np_data], tf.float32)

In [184]:
print(features)

tf.Tensor(
[[0. 1. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 0. 1.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]], shape=(496, 8), dtype=float32)


In [185]:
tf.shape(features)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([496,   8], dtype=int32)>

In [186]:
tf.shape(user_input)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([8], dtype=int32)>

In [211]:
recommendations = enhanced_similarity(features, user_input, ratings, sentiments)

In [188]:
print(recommendations)

tf.Tensor(
[0.61578315 0.44105414 0.53100735 0.5627053  0.49267226 0.37480628
 0.42846912 0.31628016 0.4078142  0.25812075 0.47223008 0.41277018
 0.47346914 0.48846912 0.50807697 0.60271776 0.4516657  0.47818094
 0.23729493 0.36752725 0.49460903 0.29801887 0.34704375 0.5034691
 0.57846916 0.33204782 0.45393598 0.3913954  0.38528293 0.5334691
 0.34410924 0.49960545 0.50253695 0.36472592 0.44772446 0.48846912
 0.48846912 0.584742   0.37704778 0.28704774 0.41463858 0.502978
 0.39096212 0.28704774 0.43175882 0.3620478  0.5034691  0.4584691
 0.3620478  0.28240407 0.5735135  0.57362264 0.44239274 0.51512754
 0.358761   0.3620478  0.3682586  0.5334691  0.33657813 0.3350768
 0.17562638 0.5149728  0.22062643 0.48846912 0.3014413  0.5184691
 0.47346914 0.32586864 0.6143906  0.40682784 0.3470478  0.45741975
 0.3620478  0.51577246 0.33256403 0.48846912 0.5184691  0.5284641
 0.43138835 0.57846916 0.81419075 0.33463216 0.47346914 0.48846912
 0.33613446 0.42846912 0.5034691  0.36397666 0.46163175 0.3

In [212]:
sorted_indices = tf.argsort(recommendations, direction='DESCENDING')

In [213]:
N = 10  # Number of recommendations you want
top_N_indices = sorted_indices[:N]

# Print the indices of the top N recommendations
print("Top N recommendation indices:", top_N_indices)

Top N recommendation indices: tf.Tensor([295  80 191 108 471 157 479 118   0 153], shape=(10,), dtype=int32)


In [214]:
top_N_df = pd.DataFrame({'Place_Id': top_N_indices.numpy()})
recommended_places = pd.merge(top_N_df+1, df_tourism, on='Place_Id', how='inner')

In [215]:
recommended_places

Place_Id                    Place_Name  Gambar  \
0       296                Rainbow Garden     NaN   
1        81  Alun Alun Selatan Yogyakarta     NaN   
2       192                   Jalan Braga     NaN   
3       109  Kauman Pakualaman Yogyakarta     NaN   
4       472           Benteng Marlborough     NaN   
5       158          Museum Ullen Sentalu     NaN   
6       480                Gereja Blenduk     NaN   
7       119          Desa Wisata Gamplong     NaN   
8         1       Monumen Nasional(Monas)     NaN   
9       154                     Candi Ijo     NaN   

                                         Description  Sentiment  Penghujan  \
0  Rainbow Garden Harapan Indah salah satu taman ...   0.838469          0   
1  Alun-alun Selatan atau yang sekarang lebih dik...   0.819314          0   
2  Jalan Braga adalah nama sebuah jalan utama di ...   0.384306          0   
3  Pakualaman adalah sebuah kecamatan di Kota Yog...   0.283588          0   
4  Benteng peninggalan kolonial Inggris yang menj...   0.755349          1   
5  Museum Ullen Sentalu, (bahasa Jawa: ꦩꦸꦱꦶꦪꦸꦩ꧀​ꦈ...   0.361746          0   
6  Gereja tertua di Semarang dengan arsitektur ko...   0.421795          0   
7  Desa Wisata Gamplong adalah desa wisata keraji...   0.764804          0   
8  Monumen Nasional atau yang populer disingkat d...   0.380043          0   
9  Candi Ijo (bahasa Jawa: ꦕꦤ꧀ꦝꦶ​ꦆꦗꦺꦴ, translit. ...   0.355382          0   

   Kemarau       Category  Budaya  Taman Hiburan  Cagar Alam  Bahari  \
0        1     Cagar Alam       0              0           1       0   
1        1  Taman Hiburan       0              1           0       0   
2        1         Budaya       1              0           0       0   
3        1         Budaya       1              0           0       0   
4        0         Budaya       1              0           0       0   
5        1         Budaya       1              0           0       0   
6        1  Tempat Ibadah       0              0           0       0   
7        1  Taman Hiburan       0              1           0       0   
8        1         Budaya       1              0           0       0   
9        1         Budaya       1              0           0       0   

   Pusat Perbelanjaan  Tempat Ibadah        City  Rating       Lat        Long  
0                   0              0     Bandung     4.6 -6.817951  107.618914  
1                   0              0  Yogyakarta     4.6 -7.811672  110.363238  
2                   0              0     Bandung     4.7 -6.915053  107.608984  
3                   0              0  Yogyakarta     5.0 -7.801035  110.375192  
4                   0              0    Bengkulu     4.5 -3.795600  102.261000  
5                   0              0  Yogyakarta     4.7 -7.597866  110.423396  
6                   0              1    Semarang     4.5 -6.970700  110.428600  
7                   0              0  Yogyakarta     4.4 -7.805523  110.237468  
8                   0              0     Jakarta     4.6 -6.175392  106.827153  
9                   0              0  Yogyakarta     4.6 -7.783828  110.511899